name: "Run Tests"

on: [push, pull_request]

jobs:
  test:

    runs-on: ubuntu-latest
    strategy:
      fail-fast: true
      matrix:
        php: [7.1, 7.2, 7.3]
        laravel: [5.0.*, 5.1.*, 5.2.*, 5.3.*, 5.4.*, 5.5.*, 5.6.*, 5.7.*, 5.8.*]
        dependency-version: [prefer-lowest, prefer-stable]
        include:
          - laravel: 5.0.*
            testbench: 3.0.*
            phpunit: ~4.8.36
          - laravel: 5.1.*
            testbench: 3.1.*
            phpunit: ~5.7.21
          - laravel: 5.2.*
            testbench: 3.2.*
            phpunit: ~5.7.21
          - laravel: 5.3.*
            testbench: 3.3.*
            phpunit: ~5.7.21
          - laravel: 5.4.*
            testbench: 3.4.*
            phpunit: ~5.7.21
          - laravel: 5.5.*
            testbench: 3.5.*
            phpunit: ~6.0
          - laravel: 5.6.*
            testbench: 3.6.*
            phpunit: ^7.0
          - laravel: 5.7.*
            testbench: 3.7.*
            phpunit: ^7.0
          - laravel: 5.8.*
            testbench: 3.8.*
            phpunit: ^7.5
        exclude:
          - laravel: 5.0.*
            php: 7.2
          - laravel: 5.0.*
            php: 7.3


    name: P${{ matrix.php }} - L${{ matrix.laravel }} - ${{ matrix.dependency-version }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Cache dependencies
        uses: actions/cache@v1
        with:
          path: ~/.composer/cache/files
          key: dependencies-laravel-${{ matrix.laravel }}-php-${{ matrix.php }}-composer-${{ hashFiles('composer.json') }}

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}
          extensions: curl, mbstring, zip, pcntl, pdo, sqlite, pdo_sqlite, iconv
          coverage: none

      - name: Install dependencies
        run: |
          composer require "orchestra/testbench:${{ matrix.testbench }}" "phpunit/phpunit:${{ matrix.phpunit }}" --no-interaction --no-update
          composer update --${{ matrix.dependency-version }} --prefer-dist --no-interaction --no-suggest

      - name: Execute tests
        run: vendor/bin/phpunit